// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package pe.etg.bbva.evalua.spring5.utilities;

public final class CUAddressBookProtos {
  private CUAddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CEPersonaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:utilities.CEPersona)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated string numbers = 4;</code>
     */
    java.util.List<java.lang.String>
        getNumbersList();
    /**
     * <code>repeated string numbers = 4;</code>
     */
    int getNumbersCount();
    /**
     * <code>repeated string numbers = 4;</code>
     */
    java.lang.String getNumbers(int index);
    /**
     * <code>repeated string numbers = 4;</code>
     */
    com.google.protobuf.ByteString
        getNumbersBytes(int index);
  }
  /**
   * Protobuf type {@code utilities.CEPersona}
   */
  public  static final class CEPersona extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:utilities.CEPersona)
      CEPersonaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CEPersona.newBuilder() to construct.
    private CEPersona(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CEPersona() {
      name_ = "";
      email_ = "";
      numbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CEPersona();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CEPersona(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                numbers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              numbers_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          numbers_ = numbers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEPersona_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEPersona_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.class, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBERS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList numbers_;
    /**
     * <code>repeated string numbers = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNumbersList() {
      return numbers_;
    }
    /**
     * <code>repeated string numbers = 4;</code>
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated string numbers = 4;</code>
     */
    public java.lang.String getNumbers(int index) {
      return numbers_.get(index);
    }
    /**
     * <code>repeated string numbers = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNumbersBytes(int index) {
      return numbers_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < numbers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, numbers_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < numbers_.size(); i++) {
          dataSize += computeStringSizeNoTag(numbers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNumbersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona)) {
        return super.equals(obj);
      }
      pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona other = (pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (!getNumbersList()
          .equals(other.getNumbersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (getNumbersCount() > 0) {
        hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumbersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code utilities.CEPersona}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:utilities.CEPersona)
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEPersona_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEPersona_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.class, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder.class);
      }

      // Construct using pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        numbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEPersona_descriptor;
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getDefaultInstanceForType() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.getDefaultInstance();
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona build() {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona buildPartial() {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona result = new pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000008) != 0)) {
          numbers_ = numbers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.numbers_ = numbers_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona) {
          return mergeFrom((pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona other) {
        if (other == pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (!other.numbers_.isEmpty()) {
          if (numbers_.isEmpty()) {
            numbers_ = other.numbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNumbersIsMutable();
            numbers_.addAll(other.numbers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList numbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNumbersIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          numbers_ = new com.google.protobuf.LazyStringArrayList(numbers_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNumbersList() {
        return numbers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public int getNumbersCount() {
        return numbers_.size();
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public java.lang.String getNumbers(int index) {
        return numbers_.get(index);
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNumbersBytes(int index) {
        return numbers_.getByteString(index);
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public Builder setNumbers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNumbersIsMutable();
        numbers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public Builder addNumbers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNumbersIsMutable();
        numbers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public Builder addAllNumbers(
          java.lang.Iterable<java.lang.String> values) {
        ensureNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, numbers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public Builder clearNumbers() {
        numbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numbers = 4;</code>
       */
      public Builder addNumbersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNumbersIsMutable();
        numbers_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:utilities.CEPersona)
    }

    // @@protoc_insertion_point(class_scope:utilities.CEPersona)
    private static final pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona();
    }

    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CEPersona>
        PARSER = new com.google.protobuf.AbstractParser<CEPersona>() {
      @java.lang.Override
      public CEPersona parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CEPersona(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CEPersona> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CEPersona> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CEAddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:utilities.CEAddressBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> 
        getPeopleList();
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getPeople(int index);
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    int getPeopleCount();
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    java.util.List<? extends pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder> 
        getPeopleOrBuilderList();
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder getPeopleOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code utilities.CEAddressBook}
   */
  public  static final class CEAddressBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:utilities.CEAddressBook)
      CEAddressBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CEAddressBook.newBuilder() to construct.
    private CEAddressBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CEAddressBook() {
      people_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CEAddressBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CEAddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                people_ = new java.util.ArrayList<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona>();
                mutable_bitField0_ |= 0x00000001;
              }
              people_.add(
                  input.readMessage(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          people_ = java.util.Collections.unmodifiableList(people_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEAddressBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEAddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.class, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.Builder.class);
    }

    public static final int PEOPLE_FIELD_NUMBER = 1;
    private java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> people_;
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    public java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> getPeopleList() {
      return people_;
    }
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    public java.util.List<? extends pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder> 
        getPeopleOrBuilderList() {
      return people_;
    }
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    public int getPeopleCount() {
      return people_.size();
    }
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getPeople(int index) {
      return people_.get(index);
    }
    /**
     * <code>repeated .utilities.CEPersona people = 1;</code>
     */
    public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder getPeopleOrBuilder(
        int index) {
      return people_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPeopleCount(); i++) {
        if (!getPeople(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < people_.size(); i++) {
        output.writeMessage(1, people_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < people_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, people_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook)) {
        return super.equals(obj);
      }
      pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook other = (pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook) obj;

      if (!getPeopleList()
          .equals(other.getPeopleList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPeopleCount() > 0) {
        hash = (37 * hash) + PEOPLE_FIELD_NUMBER;
        hash = (53 * hash) + getPeopleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code utilities.CEAddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:utilities.CEAddressBook)
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEAddressBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEAddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.class, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.Builder.class);
      }

      // Construct using pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPeopleFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (peopleBuilder_ == null) {
          people_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          peopleBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.internal_static_utilities_CEAddressBook_descriptor;
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook getDefaultInstanceForType() {
        return pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.getDefaultInstance();
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook build() {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook buildPartial() {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook result = new pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook(this);
        int from_bitField0_ = bitField0_;
        if (peopleBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            people_ = java.util.Collections.unmodifiableList(people_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.people_ = people_;
        } else {
          result.people_ = peopleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook) {
          return mergeFrom((pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook other) {
        if (other == pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook.getDefaultInstance()) return this;
        if (peopleBuilder_ == null) {
          if (!other.people_.isEmpty()) {
            if (people_.isEmpty()) {
              people_ = other.people_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePeopleIsMutable();
              people_.addAll(other.people_);
            }
            onChanged();
          }
        } else {
          if (!other.people_.isEmpty()) {
            if (peopleBuilder_.isEmpty()) {
              peopleBuilder_.dispose();
              peopleBuilder_ = null;
              people_ = other.people_;
              bitField0_ = (bitField0_ & ~0x00000001);
              peopleBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPeopleFieldBuilder() : null;
            } else {
              peopleBuilder_.addAllMessages(other.people_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getPeopleCount(); i++) {
          if (!getPeople(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> people_ =
        java.util.Collections.emptyList();
      private void ensurePeopleIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          people_ = new java.util.ArrayList<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona>(people_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder> peopleBuilder_;

      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> getPeopleList() {
        if (peopleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(people_);
        } else {
          return peopleBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public int getPeopleCount() {
        if (peopleBuilder_ == null) {
          return people_.size();
        } else {
          return peopleBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona getPeople(int index) {
        if (peopleBuilder_ == null) {
          return people_.get(index);
        } else {
          return peopleBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder setPeople(
          int index, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona value) {
        if (peopleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeopleIsMutable();
          people_.set(index, value);
          onChanged();
        } else {
          peopleBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder setPeople(
          int index, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder builderForValue) {
        if (peopleBuilder_ == null) {
          ensurePeopleIsMutable();
          people_.set(index, builderForValue.build());
          onChanged();
        } else {
          peopleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder addPeople(pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona value) {
        if (peopleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeopleIsMutable();
          people_.add(value);
          onChanged();
        } else {
          peopleBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder addPeople(
          int index, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona value) {
        if (peopleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeopleIsMutable();
          people_.add(index, value);
          onChanged();
        } else {
          peopleBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder addPeople(
          pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder builderForValue) {
        if (peopleBuilder_ == null) {
          ensurePeopleIsMutable();
          people_.add(builderForValue.build());
          onChanged();
        } else {
          peopleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder addPeople(
          int index, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder builderForValue) {
        if (peopleBuilder_ == null) {
          ensurePeopleIsMutable();
          people_.add(index, builderForValue.build());
          onChanged();
        } else {
          peopleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder addAllPeople(
          java.lang.Iterable<? extends pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona> values) {
        if (peopleBuilder_ == null) {
          ensurePeopleIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, people_);
          onChanged();
        } else {
          peopleBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder clearPeople() {
        if (peopleBuilder_ == null) {
          people_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          peopleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public Builder removePeople(int index) {
        if (peopleBuilder_ == null) {
          ensurePeopleIsMutable();
          people_.remove(index);
          onChanged();
        } else {
          peopleBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder getPeopleBuilder(
          int index) {
        return getPeopleFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder getPeopleOrBuilder(
          int index) {
        if (peopleBuilder_ == null) {
          return people_.get(index);  } else {
          return peopleBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public java.util.List<? extends pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder> 
           getPeopleOrBuilderList() {
        if (peopleBuilder_ != null) {
          return peopleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(people_);
        }
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder addPeopleBuilder() {
        return getPeopleFieldBuilder().addBuilder(
            pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.getDefaultInstance());
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder addPeopleBuilder(
          int index) {
        return getPeopleFieldBuilder().addBuilder(
            index, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.getDefaultInstance());
      }
      /**
       * <code>repeated .utilities.CEPersona people = 1;</code>
       */
      public java.util.List<pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder> 
           getPeopleBuilderList() {
        return getPeopleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder> 
          getPeopleFieldBuilder() {
        if (peopleBuilder_ == null) {
          peopleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersona.Builder, pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEPersonaOrBuilder>(
                  people_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          people_ = null;
        }
        return peopleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:utilities.CEAddressBook)
    }

    // @@protoc_insertion_point(class_scope:utilities.CEAddressBook)
    private static final pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook();
    }

    public static pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CEAddressBook>
        PARSER = new com.google.protobuf.AbstractParser<CEAddressBook>() {
      @java.lang.Override
      public CEAddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CEAddressBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CEAddressBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CEAddressBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pe.etg.bbva.evalua.spring5.utilities.CUAddressBookProtos.CEAddressBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_CEPersona_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_CEPersona_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_utilities_CEAddressBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_utilities_CEAddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\tutilities\"E\n\tCEPers" +
      "ona\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\r\n\005email\030\003" +
      " \001(\t\022\017\n\007numbers\030\004 \003(\t\"5\n\rCEAddressBook\022$" +
      "\n\006people\030\001 \003(\0132\024.utilities.CEPersonaB;\n$" +
      "pe.etg.bbva.evalua.spring5.utilitiesB\023CU" +
      "AddressBookProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_utilities_CEPersona_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_utilities_CEPersona_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_CEPersona_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Numbers", });
    internal_static_utilities_CEAddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_utilities_CEAddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_utilities_CEAddressBook_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
