# Definir el puerto del server
server:
  port: 8020

# spring.main.banner-mode=off
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url     : jdbc:postgresql://localhost:5432/bbvarquitectura
    username: postgres
    password: aemsa152027

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    generate-ddl: false
#    properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL95Dialect

  jpa:
# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.hibernate.ddl-auto = update
    hibernate:
      ddl-auto: update
    properties:
# Esta excepción no es un problema real. Ocurre durante el arranque, cuando Hibernate intenta recuperar alguna meta información de la base de datos.
      hibernate.temp.use_jdbc_metadata_defaults: false
      
    


